BEGIN
    EXECUTE INMEDIATE ' ALTER SESSION SET CURRENT_SCHEMA = TEST_USER';
    EXECUTE INMEDIATE 'CREATE TABLE PCR_AUTH_DATA (
    id VARCHAR(255) PRIMARY KEY,
    plate_id VARCHAR2(255) UNIQUE NOT NULL,
    role CLOB,
    deleted NUMBER(1) DEFAULT 0
    )';

    EXECUTE INMEDIATE ' ALTER TABLE PCR_AUTH_DATA ADD CONSTRAINT check_role CHECK (role IN (''ADMIN'', ''USER'')';
    EXECUTE INMEDIATE ' CREATE INDEX idx_auth_data_deleted ON PCR_AUHT_DATA (deleted)';
END;